#!/bin/bash

DIR=`$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )`

arch=$(if [ `uname -m`=="x86_64" ]; then echo amd64; else echo i386; fi;)
kernel_mainline="http://kernel.ubuntu.com/~kernel-ppa/mainline/"
options=( "kernel 4.3.x stable-generic" "kernel 4.3.x stable-low-latency" "latest" )
usage="$(basename "$0") [-h] [-d] [-b] [--conda n ] -- install kernel and other software easily using cli


where:
    -h, --help  show this help text
    -k, --install-kernel    install the supplied kernel or downloads
        one from the repos
    --ros     download and install ROS
    --conda    install anaconda python. Use --conda 2 or --conda 3
            depending on which python version you want to install
    --copy-settings copies the dotfiles of a previous install
    -d, --deb-packages     install .deb packages from the deb folder
    -b, --basic    install basic packages for everyday use
    -t, --tex      install packages for tex authoring and texlive
    -a, --audio    install packages for audio ripping, transcoding and editing
    -g, --games    install games such as solitaire, mahjong and others
    -p, --photo    install krita and inkscape
    --opencv    install the latest opencv
    --panamax   install Panamax, Docker manager"


basic="artha audacity bleachbit build-essential calibre cheese dia frei0r-plugins git goldendict gparted gupnp-dlna-tools gupnp-tools imagemagick keepass2 kodi miniupnpc mypaint nemo-audio-tab nemo-compare nemo-filename-repairer nemo-gtkhash nemo-image-converter nemo-media-columns nemo-seahorse openshot paman paprefs pavucontrol pulseaudio-dlna python-coherence python-nemo shotwell skype soundconverter syncthing syncthing-gtk vlc youtube-dl youtube-dlg "
wine="gnome-exe-thumbnailer wine wine-mono "
tex="texstudio texlive "
audio_edit="ardour mixxx ripit acidrip beets lame mpd "
programming="cloc meld "
games="pioneers pyscrabble gnome-games "
photo="krita inkscape "

fix_krita() {
    sudo apt-get install kdelibs-bin
    kbuildsycoca4 --noincremental
}

function die ( ) {
   echo $@
   exit 1
}

anaconda_install(){
    echo You are about to install Anaconda $1
    read -p "Continue (y/n)?  "
	[ "$REPLY" == y ] || die "Exiting..."
    mkdir tmp
    if [ $arch == "amd64" ]; then
        file=Anaconda$1-2.4.1-Linux-x86_64.sh
    else
        file=Anaconda$1-2.4.1-Linux-x86.sh
    fi
    printf "Downloading $file ...\n"
    curl -# -o tmp/$file https://repo.continuum.io/archive/$file
    md5sum -c
    sh tmp/$file
    rm -rf tmp
}




panamax_install(){
    echo You are about to install Panamax
    read -p "Continue (y/n)?  "
	[ "$REPLY" == y ] || die "Exiting..."
    mkdir tmp
    printf "Installx86_64ing dependencies\n"
    printf "Virtualbox...\n"
    sudo apt-get install virtualbox
    printf "Vagrant...\n"
    printf "Downloading Vagrant\n"
    curl -o tmp/sha256sums https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_SHA256SUMS
    if [ $arch == "amd64" ]; then
        file=vagrant_1.8.1_x86_64.deb
    else
        file=vagrant_1.8.1_i686.deb
    fi
    printf "Downloading vagrant_1.8.1_$ver.deb ...\n"
    curl -# -o tmp/$file https://releases.hashicorp.com/vagrant/1.8.1/$file
	cat tmp/sha256sums | grep $file > tmp/sums
	cd tmp
    sha256sum -c sums | grep OK || break
    dpkg -i $file
    printf "Downloading and installing Panamax...\n"
    curl -# -o ubuntu.sh http://download.panamax.io/installer/ubuntu.sh
    bash ubuntu.sh
	cd ../
    rm -rf tmp
}




ros_install(){
    echo You are about to install ROS $2
    read -p "Continue (y/n)?  "
	[ "$REPLY" == y ] || die "Exiting..."
    mkdir tmp
    curl -# -o tmp/ros_install.sh https://raw.githubusercontent.com/oroca/oroca-ros-pkg/master/ros_install.sh
    chmod 755 tmp/ros_install.sh
    ./tmp/ros_install.sh $1 $2
    rm -rf tmp
}


opencv_install(){
	mkdir tmp
	printf "Downloading install scripts..."
	git clone https://github.com/jayrambhia/Install-OpenCV.git
	read -p "Continue (y/n)?  "
	[ "$REPLY" == y ] || rm -rf Install-OpenCV && die "Exiting..."
    ./Install-OpenCV/Ubuntu/opencv_latest.sh
	rm -rf Install-OpenCV
}

install_kernel(){
    if [ -d "kernel" ]; then
        echo 'Found kernel folder. Installing the supplied kernel';
        echo installing kernel...;
        dpkg -i kernel/*.deb;
    else
        printf 'WARNING: kernel folder not found!\n\n'
        # Select loop
        select opt in "${options[@]}"; do
            case $opt in
                "kernel 4.3.x stable-generic")
                    ver="v4.3.4-wily/";
                    ed="generic";
                    break
                    ;;
                "kernel 4.3.x stable-low-latency")
                    ver="v4.3.4-wily/";
                    ed="lowlatency";
                    break
                    ;;
                "latest")
                    ver="v4.5-rc1-wily/";
                    ed="generic";
                    break
                    ;;
                *)
                    echo "Error select option 1..3";;
            esac;
        done;
        k_image=$(curl --silent $kernel_mainline/$ver/ | grep -o "linux-image-[a-z0-9\.-]*$ed\_[a-z0-9\.-]*_$arch.deb" | uniq)
        k_header_all=$(curl --silent $kernel_mainline/$ver/ | grep -o "linux-headers-[0-9\.-]*_[a-z0-9\.-]*_all.deb" | uniq)
        k_header=$(curl --silent $kernel_mainline/$ver/ | grep -o "linux-headers-[a-z0-9\.-]*-$ed\_[a-z0-9\.-]*_$arch.deb" | uniq)
        printf 'Making directory kernel and downloading the kernel files...\n\n'
	mkdir kernel
	echo Downloading $k_image...
	curl -# -o kernel/$k_image $kernel_mainline/$ver/$k_image
	echo Downloading $k_header_all ...
	curl -# -o kernel/$k_header_all $kernel_mainline/$ver/$k_header_all
	echo Downloading $k_header ...
	curl -# -o kernel/$k_header $kernel_mainline/$ver/$k_header
    printf "Installing kernel: $k_image\n\n"
    read -p "Continue (y/n)?  "
    [ "$REPLY" == y ] || die "Exiting..."
	dpkg -i kernel/*.deb;
    fi
}


install_packages(){
    sudo apt-get update;
	sudo apt-get -f -s install $1;
}




while :; do
    case $1 in
        -h|-\?|--help)   # Call a "show_help" function to display a synopsis, then exit.
            echo "$usage"
	    exit
            ;;
        --conda)       # Takes an option argument, ensuring it has been specified.
            if [ -n "$2" ]; then
                if [ "$2" == "2" ] || [ "$2" == "3" ]; then
                    conda_v=$2
                    shift
                    anaconda_install $conda_v
                else
                    printf 'ERROR: "--conda" requires a version 2 or 3.\n' >&2
                    exit 1
                fi
            else
                printf 'ERROR: "--file" requires a non-empty option argument.\n' >&2
                exit 1
            fi
            ;;
        --ros)
            ros=true
            ;;
	    -k|--install-kernel)
            k=true
            ;;
	    --opencv)
            opencv_install
	        ;;
        --panamax)
            panamax_install
            ;;
        --copy-settings)
            cp_sett=true
            ;;
        -b|--basic)
            packages="$packages$basic"
            printf "Adding the neccessary repositories...\n"
            # Add the release PGP keys:
            curl -s https://syncthing.net/release-key.txt | sudo apt-key add -

            # Add the "release" channel to your APT sources:
            echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list

            # For syncthing-gtk
            sudo add-apt-repository -y ppa:nilarimogard/webupd8

            sudo apt-add-repository -y ppa:qos/pulseaudio-dlna
            sudo apt-add-repository -y ppa:team-xbmc/ppa
            sudo apt-add-repository -y ppa:videolan/stable-daily
            sudo apt-add-repository -y ppa:mc3man/trusty-media
            ;;
        -t|--tex)
            packages="$packages$tex"
            ;;
        -g|--games)
            packages="$packages$games"
            ;;
        -a|--audio)
            packages="$packages$audio_edit"
            ;;
	-p|--photo)
            packages="$packages$photo"
	    fixkrita=true
            ;;
	-d|--deb-packages)
    	    count=`ls -1 deb/*.deb 2>/dev/null | wc -l`
    	    if [ $count != 0 ]; then
    			d=true

    	    else
    		printf 'ERROR: In order to use the "--deb-packages" you need a folder with .deb files' >&2
    		exit
    	    fi
            ;;
        -v|--verbose)
            verbose=$((verbose + 1)) # Each -v argument adds 1 to verbosity.
            ;;
        --)              # End of all options.
            shift
            break
            ;;
        -?*)
            printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
            ;;
        *)               # Default case: If no more options then break out of the loop.
            break
    esac

    shift
done


# Main process
echo -n 'Checking if "curl" is installed on your system...'
dpkg -l | grep -qw curl || $(printf 'curl not found! Installing now.\n\n'; apt-get install curl)
printf 'curl is installed.\n\n'

if [ $k ]; then
    install_kernel
fi
if [ $d ]; then
	for package in deb/*.deb; do
		echo installing "$package"
        sudo dpkg -i $package
	done;
    apt-get -f install
fi
echo $packages
if [ -n "$packages"  ]; then
    install_packages "$packages"
    if [ $fixkrita ]; then
	fix_krita;
    fi
fi

if [ $cp_sett ]; then
    if [ -e "dotfiles"]; then
        rsync -hP dotfiles ~/ && printf "Trasfer completed." || printf "An ERROR occured."
    else
        printf "You don't have any settings to copy, ABORTING!\n\n"
    fi
fi

if [ $ros ]; then
    echo -n "Give a name for your catkin workspace: " && read catkin
    select ros_distro in indigo jade hydro; do
        ros_install $catkin $ros_distro
        break;
    done;
fi
